apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-journey

resources:
  - deployment.yaml
  - imagestream.yaml
  - namespace.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml