---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-server
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
